App\Entity\Location:
    properties:
        city:
            - NotBlank: ~
        country:
            - NotBlank: ~
            - Length:
                min: 2
                max: 2

        latitude:
            - NotBlank: ~
            - Range:
                min: -90
                max: 90
        longtitude:
            - NotBlank: ~
            - Range:
                min: -180
                max: 180