App\Entity\Measurement:
    properties:
        location:
            - NotBlank: ~
        date:
            - NotBlank: ~
        temperature:
            - NotBlank: ~
            - Range:
                min: -100
                max: 100